Feature/#60
suzuka-kosen-festa/2022-HP pull request #123
Opened 2022-08-10 09:28 UTC by Sansai-snct

# 📝 what

- Footerを作成した

# 😎 why

- 必要だったので生やした

# ✅ check

- [x] このリポジトリの[ルール](https://github.com/suzuka-kosen-festa/2022-HP/wiki/%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB)に則っているか
- [x] テストを書いた or もう書いてある or 書く必要のない修正
- [x] 動作検証をした

# ℹ️ issue

close #60

2022-08-10 09:52 UTC, re-taro requested changes

2022-08-10 09:52 UTC, re-taro commented on src/components/organisms/footer/footer.stories.tsx
> +export default { args: { title: "Footer" }, component: Footer } as ComponentMeta<typeof Footer>;
propにtitleが無いように見えます

```suggestion
export default { component: Footer } as ComponentMeta<typeof Footer>;
```

2022-08-10 09:52 UTC, re-taro commented on src/components/organisms/footer/footer.test.tsx
> +  test("take snap shot", () => {
テスト落ちています。

2022-08-10 09:52 UTC, re-taro commented on src/components/organisms/footer/footer.test.tsx
> +});
organisimsかどうかのテスト、roleのテストもつけてください

2022-08-10 09:52 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +  <footer css={tw`absolute bottom-0 w-screen`}>
後々死ぬのでabsoluteはやめましょう

```suggestion
  <footer css={tw`bottom-0 w-screen`}>
```

2022-08-10 09:52 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +  <footer css={tw`absolute bottom-0 w-screen`}>
footerが自分の居場所を決めるのではなく親が決めるようにしましょう

```suggestion
  <footer css={tw`absolute w-screen`}>
```

2022-08-10 09:52 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +    <Text css={tw`bg-black text-center p-2`}>&copy; 第57回鈴鹿高専祭実行委員会</Text>
mobileではcenterになっていません

```suggestion
    <Text css={tw`bg-black p-2`}>&copy; 第57回鈴鹿高専祭実行委員会</Text>
```

2022-08-10 09:52 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +    <Text css={tw`bg-black text-center p-2`}>&copy; 第57回鈴鹿高専祭実行委員会</Text>
paddingで位置制御をするとテキストサイズが壊れます

```suggestion
    <Text css={tw`bg-black text-center`}>&copy; 第57回鈴鹿高専祭実行委員会</Text>
```

2022-08-10 10:36 UTC, re-taro requested changes

2022-08-10 10:36 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +export { Footer };
exportするだけじゃなくて、layoutに組み込んでください。

2022-08-10 11:54 UTC, re-taro commented
prの名前を変えてください

2022-08-11 13:42 UTC, re-taro commented
RCを修正した場合は修正したコミットハッシュをRCに書いてからresolveしてください。

2022-08-11 13:53 UTC, re-taro requested changes

2022-08-11 13:53 UTC, re-taro commented on src/components/organisms/footer/__snapshots__/footer.test.tsx.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
snap shotを更新してください。
それ用のコマンドを用意したはずです。

2022-08-11 13:53 UTC, re-taro commented on src/components/organisms/footer/footer.test.tsx
> +  test("to be [role=organisms]", () => {
roleにorganismsというものは存在しません。
WAI-ARIAについて調べてください。

2022-08-11 13:53 UTC, re-taro commented on src/components/organisms/footer/footer.test.tsx
> +import { composeStories } from "@storybook/testing-react";
testがanyなのは本当に謎なのでもう一回書き直してみてください。

2022-08-11 13:53 UTC, re-taro commented on src/components/templates/layout/index.tsx
> +import { Footer } from "src/components/organisms/footer";
絶対パスはやめてください。ESLintで禁止にしているはずです。していないにしても、デプロイ時にいらないバグのもとになりかねないのでやめてください。

2022-08-11 13:53 UTC, re-taro commented on src/components/templates/layout/index.tsx
> +      <Footer />
layoutが変わったのでsnap shotも更新してください。

2022-08-11 14:52 UTC, re-taro commented on src/components/templates/layout/index.tsx
> +import { Footer } from "src/components/organisms/footer";
![image](https://user-images.githubusercontent.com/68799469/184162828-3f6dd2db-b10f-46f8-9a55-2e19863f0221.png)

2022-08-11 15:11 UTC, Sansai-snct commented on src/components/templates/layout/index.tsx
> +import { Footer } from "src/components/organisms/footer";
fix at [5535cce](https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/5535cceb65142ccd2f76125b42b8b904600362e4)

2022-08-11 15:37 UTC, Sansai-snct commented on src/components/organisms/footer/footer.test.tsx
> +  test("to be [role=organisms]", () => {
contentinfoでok?

2022-08-11 16:48 UTC, Sansai-snct commented on src/components/templates/layout/index.tsx
> +      <Footer />
f23fffff55b9487cae091174f38096e8d89946e8

2022-08-11 16:49 UTC, Sansai-snct commented on src/components/organisms/footer/footer.test.tsx
> +import { composeStories } from "@storybook/testing-react";
[b61a462](https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/b61a4624cef381fd8172671b72ddcab04319529f)

2022-08-11 16:50 UTC, Sansai-snct commented on src/components/organisms/footer/footer.test.tsx
> +  test("to be [role=organisms]", () => {
[2390760](https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/239076098d6a72b3b6ae373b4501514565b8ae26)

2022-08-11 16:50 UTC, Sansai-snct commented on src/components/organisms/footer/__snapshots__/footer.test.tsx.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
[f23ffff](https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/f23fffff55b9487cae091174f38096e8d89946e8)

2022-08-11 16:51 UTC, Sansai-snct commented on src/components/organisms/footer/footer.test.tsx
> +});
[f78cce1](https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/f78cce14dffc647e31bd324e11342cd06a029ecc)

2022-08-11 16:51 UTC, Sansai-snct commented on src/components/organisms/footer/footer.test.tsx
> +  test("take snap shot", () => {
[b61a462](https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/b61a4624cef381fd8172671b72ddcab04319529f)

2022-08-18 02:36 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +    <Text css={tw`bg-black text-center p-2`}>&copy; 第57回鈴鹿高専祭実行委員会</Text>
デザインが変わりtext-centerとなりました

2022-08-18 02:52 UTC, re-taro requested changes

2022-08-18 02:52 UTC, re-taro commented on .github/workflows/test.yml
> +    runs-on: windows-latest
ubuntuに戻しておいてください

```suggestion
    runs-on: ubuntu-latest
```

2022-08-18 02:52 UTC, re-taro commented on src/components/atoms/anchor-text/anchor-text.stories.tsx
> +  role: "link",
```suggestion
  role: "link",
  tabindex: 0,
```

2022-08-18 02:52 UTC, re-taro commented on src/components/atoms/anchor-text/anchor-text.stories.tsx
> +  args: { children: data.sentence, href: data.link, role: data.role },
```suggestion
  args: { children: data.sentence, href: data.link, role: data.role, tabIndex: data.tabindex },
```

2022-08-18 02:52 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +    <AnchorText href={link} target={"_blank"} rel={"noopener noreferrer"} role={"link"}>
```suggestion
    <AnchorText href={link} target={"_blank"} rel={"noopener noreferrer"} role={"link"} tabIndex={0}>
```

2022-08-18 07:12 UTC, Sansai-snct commented on .github/workflows/test.yml
> +    runs-on: windows-latest
https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/8a45cca0c8e026313c706cf801edc7048c3197ea

2022-08-18 07:12 UTC, Sansai-snct commented on src/components/atoms/anchor-text/anchor-text.stories.tsx
> +  role: "link",
https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/5e3841fa9d0549f8ecef0c125c0aea8b01b4414e

2022-08-18 07:12 UTC, Sansai-snct commented on src/components/atoms/anchor-text/anchor-text.stories.tsx
> +  args: { children: data.sentence, href: data.link, role: data.role },
https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/5e3841fa9d0549f8ecef0c125c0aea8b01b4414e

2022-08-18 07:13 UTC, Sansai-snct commented on src/components/organisms/footer/index.tsx
> +    <AnchorText href={link} target={"_blank"} rel={"noopener noreferrer"} role={"link"}>
https://github.com/suzuka-kosen-festa/2022-HP/pull/123/commits/0e80f5e478572a574ba8f7bc130b44ab9dce6649

2022-08-18 07:15 UTC, Sansai-snct commented
テスト落ちまくってるので今から治します

2022-08-18 09:22 UTC, re-taro requested changes

2022-08-18 09:22 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +const FooterBox = tw.footer`bg-black text-center p-2 w-screen`;
p-2ではないと思われます

2022-08-18 09:35 UTC, Sansai-snct commented on src/components/organisms/footer/index.tsx
> +const FooterBox = tw.footer`bg-black text-center p-2 w-screen`;
テキスト周りの余白を取りたいんだけど、こういう場合は別でスタイル当てるの？

2022-08-18 10:02 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +const FooterBox = tw.footer`bg-black text-center p-2 w-screen`;
いやp-2だと固定じゃないですか、ちゃんと可変にしてください。

2022-08-18 10:10 UTC, Sansai-snct commented on src/components/organisms/footer/index.tsx
> +const FooterBox = tw.footer`bg-black text-center p-2 w-screen`;
そりゃまだ治してないからな... 
前のレビューでも言われてたからpaddingを使うとまずいのかどうかききたかった

2022-08-18 10:11 UTC, Sansai-snct commented on src/components/organisms/footer/index.tsx
> +const FooterBox = tw.footer`bg-black text-center p-2 w-screen`;
前のレビューだとpadding自体に問題があるようだったので
修正が遅いのはすみません

2022-08-18 10:16 UTC, re-taro commented on src/components/organisms/footer/index.tsx
> +const FooterBox = tw.footer`bg-black text-center p-2 w-screen`;
あ、そういうことね。font-sizeを完全な可変にしたので問題ないはずです、paddingで指定してください

2022-08-18 10:22 UTC, Sansai-snct commented on src/components/organisms/footer/index.tsx
> +const FooterBox = tw.footer`bg-black text-center p-2 w-screen`;
今大絶賛モバイルだと下の余白の方が長くなる問題を解決中です

2022-08-19 14:19 UTC, re-taro approved these changes

2022-08-19 14:20 UTC, merged